# .pre-commit-config.yaml (레포 루트)

default_language_version:
  golang: "1.24.6"   # 팀 표준에 맞춰 조정: 예) "1.23.2" 또는 "1.24.6"


repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.20.0        # 도구 버전 고정
    hooks:
      - id: terraform-docs-go
        name: terraform-docs (modules)
        args: [ "--config", ".terraform-docs.yaml", "./modules" ]
        pass_filenames: false

      - id: terraform-docs-go
        name: terraform-docs (dev)
        args: [ "--config", ".terraform-docs.yaml", "./dev" ]
        pass_filenames: false

      - id: terraform-docs-go
        name: terraform-docs (stage)
        args: [ "--config", ".terraform-docs.yaml", "./stage" ]
        pass_filenames: false

      - id: terraform-docs-go
        name: terraform-docs (prod)
        args: [ "--config", ".terraform-docs.yaml", "./prod" ]
        pass_filenames: false