apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-admins-binding
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "false"
  labels:
    app.kubernetes.io/name: platform-admin
    rbac.example.com/team: platform-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: platform-admins
- kind: ServiceAccount
  name: platform-admin-automation
  namespace: kube-system
