apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-admin-automation
  namespace: kube-system
  labels:
    app.kubernetes.io/name: platform-admin-automation
    app.kubernetes.io/part-of: platform-admin-tooling
secrets: []
