apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-ops-binding
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "false"
  labels:
    app.kubernetes.io/name: platform-ops
    rbac.example.com/team: platform-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-ops
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: platform-ops
- kind: ServiceAccount
  name: platform-ops-maintenance
  namespace: operations
